name: Publish Jekyll Site as GitHub Package

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Jekyll Site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Create Package
        run: |
          mkdir -p dist
          mv _site/* dist/
        working-directory: .

      - name: Publish Package
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

