name: Publish Jekyll Site as GitHub Package

on:
  push:
    branches:
      - gh-pages  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Adjust the Ruby version as needed

      - name: Install Bundler
        run: gem install bundler
        env:
          GEM_HOME: ${{ github.workspace }}/.gems
          PATH: ${{ github.workspace }}/.gems/bin:$PATH

      - name: Install Dependencies
        run: |
          bundle config set path '.gems'
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Create Package
        run: |
          mkdir -p dist
          mv _site/* dist/
        working-directory: .

      - name: Publish Package
        run: |
          echo "Publishing Jekyll site as a GitHub Package..."
          echo "Creating package directory..."
          mkdir -p package
          mv dist/* package/
          echo "Publishing package..."
          echo "NPM_TOKEN: ${{ secrets.GH_TOKEN }}"
          echo "PACKAGE_DIR: ${{ github.workspace }}/package"
          curl -X PUT -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${GITHUB_REPOSITORY}/contents/package?ref=${GITHUB_REF}" --data-binary @- << EOF
          {
            "message": "Publish Jekyll site as GitHub Package",
            "committer": {
              "name": "${{ github.actor }}",
              "email": "${{ github.actor }}@users.noreply.github.com"
            },
            "content": "$(base64 -w0 ${github.workspace}/package/*)"
          }
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
